# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c19bdd07-c3ed-4998-a1ca-57a88aa91e79";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c19bdd07-c3ed-4998-a1ca-57a88aa91e79".device = "/dev/disk/by-uuid/c19bdd07-c3ed-4998-a1ca-57a88aa91e79";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/00A1-6219";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3c9cb9b5-c350-42ed-866d-c452ebe0763a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
