# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6c6fdddf-3eb2-4aca-8722-b1f0b7edef9f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6c6fdddf-3eb2-4aca-8722-b1f0b7edef9f".device = "/dev/disk/by-uuid/6c6fdddf-3eb2-4aca-8722-b1f0b7edef9f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5458-4DF4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-416c1806-20a2-40f9-ae08-a7ee3b7f86a3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
