# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-14c55468-f0ee-419d-9456-e59057c0df1f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-14c55468-f0ee-419d-9456-e59057c0df1f".device = "/dev/disk/by-uuid/14c55468-f0ee-419d-9456-e59057c0df1f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9862-0B51";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

services.xserver.videoDrivers = [ "nvidia" ];

hardware.nvidia = {
  open = true;              # change to false if older GPU
  modesetting.enable = true;
  nvidiaSettings = true;
};


}
